services:
    rdf4j:
        container_name: rdf4j
        image: spcleth/kgot-rdf4j:latest
        ports:
            - "${PORT}:8080"
        healthcheck:
            test: wget http://localhost:8080/rdf4j-server/repositories || exit 1
            interval: 10s
            timeout: 20s
            retries: 3
            start_period: 20s
        networks:
            knowledge_graph:
                aliases:
                    - rdf4j-knowledge-graph

networks:
    knowledge_graph:
        name: knowledge_graph
        driver: bridge
